backend:
  name: git-gateway
  branch: main

media_folder: "assets/uploads"
public_folder: "/uploads"

collections:
  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: false
    description: >
      Add posts about recent activities, news, and stories related to your mission.
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "post" }
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Author",
          name: "author",
          widget: "relation",
          collection: "authors",
          display_fields: [display_name],
          search_fields: [display_name],
          value_field: "name",
          required: false,
        }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "works"
    label: "Recent Works"
    folder: "content/works"
    create: true
    slug: "{{year}}-{{slug}}"
    editor:
      preview: false
    description: >
      Add or update your work experience entries here.
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Company", name: "company", widget: "string" }
      - { label: "Start Date", name: "start_date", widget: "string" }
      - { label: "End Date", name: "end_date", widget: "string", default: "Present" }

  - name: "product"
    label: "Product"
    folder: "content/product.json"
    create: true
    editor:
      preview: false
    description: >
      List new products. Make sure to provide all necessary details.
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "product" }
      - { label: "Title", name: "title", widget: "string", required: true }
      - { label: "Slug", name: "slug", widget: "string", required: true, pattern: ['^[a-z0-9]+(?:-[a-z0-9]+)*$', "Must be lowercase and hyphenated."] }
      - { label: "Price", name: "price", widget: "number", required: true }
      - { label: "Description", name: "description", widget: "markdown" }
      - { label: "Image", name: "image", widget: "image", required: true }

  - name: "gallery"
    label: "Gallery"
    create: false
    description: >
      Upload photos and videos from our events and projects. Use this space to visually share our story and impact. These images will be shown in the carousel.
    files:
      - label: "Gallery"
        name: "gallery"
        file: "cms/_gallery/gallery.md"
        fields:
          - {
              label: "Images",
              name: "images",
              widget: "image",
              choose_url: true,
              media_library: { config: { multiple: true, max_files: 999 } },
            }
